const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  salvarCadastro: (dados) => ipcRenderer.invoke('salvar-cadastro', dados),
  salvarNota: (nome, conteudo) => ipcRenderer.invoke('salvar-nota', nome, conteudo),
  listarNotas: () => ipcRenderer.invoke('listar-notas'),
  lerNota: (nome) => ipcRenderer.invoke('ler-nota', nome),
  criptografar: (texto, senha) => ipcRenderer.invoke('criptografar', texto, senha),
  descriptografar: (conteudo, senha) => ipcRenderer.invoke('descriptografar', conteudo, senha),
  getSenhaUsuario: () => ipcRenderer.invoke('get-senha-usuario'),
  armazenarSenha: (senha) => ipcRenderer.invoke('armazenar-senha', senha),
  lerUsuario: () => ipcRenderer.invoke('ler-usuario'),
  excluirNota: (nome) => ipcRenderer.invoke('excluir-nota', nome),
  exportarNotas: (html, nome) => ipcRenderer.invoke('exportar-notas', html, nome),
  abrirVisualizacaoNotas: (html) => ipcRenderer.invoke('abrir-visualizacao-notas', html),
  enviarEmail: (dados) => ipcRenderer.invoke('enviar-email-dirigente', dados),
  gerarPdfAnexosParaEmail: (conteudos, nomes, tipo) => ipcRenderer.invoke('gerar-pdf-anexos-email', conteudos, nomes, tipo),
  obterCadastro: () => ipcRenderer.invoke('obter-cadastro'),
  validarSenha: (senha) => ipcRenderer.invoke('validar-senha', senha),
  validarSenhaHash: (senha) => ipcRenderer.invoke('validar-senha-hash', senha),
  gerarPdf: (html, nomeArquivo, salvarNoDisco = true) => ipcRenderer.invoke('gerar-pdf', html, nomeArquivo, salvarNoDisco),
  enviarToken: (token) => ipcRenderer.invoke('enviar-token', token),
  obterNomeAluno: () => ipcRenderer.invoke('obter-nome-aluno'),
  enviarEmailContato: (assunto, mensagem) => ipcRenderer.invoke('enviarEmailContato', assunto, mensagem),
});
